[build]
  # This is a pure static HTML/CSS/JS site - no build process needed
  command = ""
  publish = "."
  
# Explicitly disable any framework detection
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-fund --no-audit"

# Skip dependency installation completely
[build.processing]
  skip_processing = false